--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: currencyeurekaserver
    version: v1
  name: currencyeurekaserver
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: currencyeurekaserver
    version: v1
  type: NodePort